{% set name = "calphy" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca0e5cfac30665a30f044b2627b0828a70a20f0f4e5584c0ea83386a998e6580

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - calphy = calphy.kernel:main
    - calphy_kernel = calphy.queuekernel:main
    - calphy_run_averaging = calphy.clitools:run_averaging
    - calphy_process_averaging = calphy.clitools:process_averaging
    - calphy_run_integration = calphy.clitools:run_integration
    - calphy_process_integration = calphy.clitools:process_integration
    - calphy_phase_diagram = calphy.clitools:phase_diagram

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - tqdm
    - scipy
    - numpy
    - mendeleev
    - pylammpsmpi >=0.2.37
    - pyyaml
    - lammps >=2023.03.28
    - pytest
    - mpi4py
    - uncertainties
    - pydantic >=2.3.0
    - pyscal3

test:
  imports:
    - calphy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ICAMS/calphy
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python library and command line interface for automated free energy calculations'
  description: |
    A Python library and command line interface for automated free energy
    calculations
  doc_url: https://calphy.org/
  dev_url: https://github.com/ICAMS/calphy

extra:
  recipe-maintainers:
    - srmnitc
    - jan-janssen
