{% set name = "calphy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d83a7b86f2b4ec465a50d45872adfbe3f5e1df41339fa4ca1ff9095e306ef42

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - calphy = calphy.kernel:main
    - calphy_kernel = calphy.queuekernel:main

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - matplotlib-base
    - tqdm
    - numpy
    - mendeleev
    - pyscal
    - pylammpsmpi
    - pyyaml
    - lammps
    - pytest
    - mpi4py

test:
  imports:
    - calphy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ICAMS/calphy
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python library and command line interface for automated free energy calculations'
  description: |
    A Python library and command line interface for automated free energy
    calculations
  doc_url: https://calphy.org/
  dev_url: https://github.com/ICAMS/calphy

extra:
  recipe-maintainers:
    - srmnitc
    - jan-janssen
