{% set name = "calphy" %}
{% set version = "1.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 719814626246a2e887ad0f467a3faf39e6dbd6e5ef87c3efe223841dfd7726de

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - calphy = calphy.kernel:main
    - calphy_kernel = calphy.queuekernel:main
    - calphy_run_averaging = calphy.clitools:run_averaging
    - calphy_process_averaging = calphy.clitools:process_averaging
    - calphy_run_integration = calphy.clitools:run_integration
    - calphy_process_integration = calphy.clitools:process_integration
            
requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - matplotlib-base
    - tqdm
    - scipy
    - numpy
    - mendeleev
    - pylammpsmpi
    - pyyaml
    - lammps >=2023.03.28
    - pytest
    - mpi4py
    - uncertainties
    - pydantic >=2.3.0
    - pyscal3

test:
  imports:
    - calphy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ICAMS/calphy
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python library and command line interface for automated free energy calculations'
  description: |
    A Python library and command line interface for automated free energy
    calculations
  doc_url: https://calphy.org/
  dev_url: https://github.com/ICAMS/calphy

extra:
  recipe-maintainers:
    - srmnitc
    - jan-janssen
