{% set name = "calphy" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 148d52071d857c15c23f68a57f437fc725615e0b7696f05d2c96e716636a21bf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - calphy = calphy.kernel:main
    - calphy_kernel = calphy.queuekernel:main
    - calphy_phase_diagram = calphy.clitools:phase_diagram

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - tqdm
    - scipy
    - numpy >=2
    - pandas
    - mendeleev
    - pylammpsmpi >0.4.1
    - pyyaml
    - lammps >=2023.03.28
    - pytest
    - mpi4py
    - pydantic >=2.3.0
    - pyscal3
    - pyarrow

test:
  imports:
    - calphy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/ICAMS/calphy
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python library and command line interface for automated free energy calculations'
  description: |
    A Python library and command line interface for automated free energy
    calculations
  doc_url: https://calphy.org/
  dev_url: https://github.com/ICAMS/calphy

extra:
  recipe-maintainers:
    - srmnitc
    - jan-janssen
